/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  // Import or define the docs variable containing the sidebar configuration
// Define the sidebar configuration under the 'mySidebar' key
const docs = {
  mySidebar: {
    // Existing and new sidebar items
    'Portfolio': ['tutorial-basics/portfolio.md'],
    // Add more sidebar items as needed
  },
}

// Export the entire sidebar configuration
module.exports = docs;
docs/tutorial-basics/portfolio.md